url: http://torinotechscene.it
baseurl:

# Site settings
title: Torino Tech Scene
email: bob@linux.it
description: "Torino Tech Scene, il punto d'accesso per gli smanettoni di Torino"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

social:
  - title: twitter
    url: http://twitter.com/torinotechscene

  - title: github
    url: http://github.com/madbob/torinotechscene

# Build settings
markdown: kramdown
permalink: pretty
